[workspace]
resolver = "3"
members = ["kernel", "userspace"]

[profile.dev]
panic = "abort"
opt-level = 3

[profile.release]
panic = "abort"
opt-level = 3
# lto = true
# codegen-units = 1
debug = false
